from importlib import import_module

_MODEL_MODULES = (
    "cart",
    "cart_item",
    "category",
    "category_suggestion",
    "chat_message",
    "chat_session",
    "coupon",
    "coupon_usage",
    "email_verifycation_token",
    "inventory",
    "inventory_transaction",
    "moderation_log",
    "notification",
    "order",
    "order_cancellation",
    "order_item",
    "order_status_log",
    "password_reset_token",
    "payment",
    "payment_order",
    "phone_verifycation_otp",
    "product",
    "product_category",
    "product_image",
    "product_review",
    "product_variant",
    "refund",
    "review_image",
    "search_log",
    "seller_document",
    "seller_payout",
    "seller_profile",
    "seller_statistics",
    "shipment",
    "user",
    "user_address",
    "user_role",
    "user_session",
    "violation_report",
    "violation_report_image",
)

for module_name in _MODEL_MODULES:
    import_module(f"{__name__}.{module_name}")
