"""add_reply_to_id_to_seller_messages

Revision ID: 0b911fc87174
Revises: 115e4ae9fa19
Create Date: 2026-08-06 07:00:48.579694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0b911fc87174'
down_revision: Union[str, Sequence[str], None] = '115e4ae9fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_messages', sa.Column('reply_to_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'seller_messages', 'seller_messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller_messages', type_='foreignkey')
    op.drop_column('seller_messages', 'reply_to_id')
    # ### end Alembic commands ###
