"""Add seller chat models

Revision ID: 115e4ae9fa19
Revises: 97c34cf5edba
Create Date: 2026-08-06 09:17:12.483053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '115e4ae9fa19'
down_revision: Union[str, Sequence[str], None] = '97c34cf5edba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_conversations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('shop_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seller_conversations_customer_id', 'seller_conversations', ['customer_id'], unique=False)
    op.create_index('ix_seller_conversations_shop_id', 'seller_conversations', ['shop_id'], unique=False)
    op.create_index('ix_seller_conversations_status', 'seller_conversations', ['status'], unique=False)
    op.create_table('seller_messages',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'SELLER', 'SYSTEM'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_type', sa.Enum('PRODUCT', 'ORDER', 'IMAGE', 'VIDEO'), nullable=True),
    sa.Column('attachment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['seller_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seller_messages_conversation_id', 'seller_messages', ['conversation_id'], unique=False)
    # op.add_column('seller_statistics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # op.alter_column('support_messages', 'sender_type',
    #            existing_type=mysql.ENUM('CUSTOMER', 'SUPPORTER', collation='utf8mb4_unicode_ci'),
    #            type_=sa.Enum('CUSTOMER', 'SUPPORTER', 'SYSTEM'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_messages', 'sender_type',
               existing_type=sa.Enum('CUSTOMER', 'SUPPORTER', 'SYSTEM'),
               type_=mysql.ENUM('CUSTOMER', 'SUPPORTER', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('seller_statistics', 'updated_at')
    op.drop_index('ix_seller_messages_conversation_id', table_name='seller_messages')
    op.drop_table('seller_messages')
    op.drop_index('ix_seller_conversations_status', table_name='seller_conversations')
    op.drop_index('ix_seller_conversations_shop_id', table_name='seller_conversations')
    op.drop_index('ix_seller_conversations_customer_id', table_name='seller_conversations')
    op.drop_table('seller_conversations')
    # ### end Alembic commands ###
