"""Add shipping providers

Revision ID: 3d929640a551
Revises: a524958c1990
Create Date: 2026-08-10 18:28:06.856885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d929640a551'
down_revision: Union[str, Sequence[str], None] = 'a524958c1990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_shipping_providers',
    sa.Column('seller_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('shipping_provider_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipping_provider_id'], ['shipping_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seller_id', 'shipping_provider_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller_shipping_providers')
    # ### end Alembic commands ###
