"""replace unique constraint with index

Revision ID: 41f9aa859a53
Revises: b9e8d7c6f5a4
Create Date: 2026-07-24 08:24:08.456547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f9aa859a53'
down_revision: Union[str, Sequence[str], None] = 'b9e8d7c6f5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_violation_reports_reporter_id', 'violation_reports', ['reporter_id'], unique=False)
    op.drop_index(op.f('uq_violation_reports_reporter_product'), table_name='violation_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_violation_reports_reporter_product'), 'violation_reports', ['reporter_id', 'product_id'], unique=True)
    op.drop_index('ix_violation_reports_reporter_id', table_name='violation_reports')
    # ### end Alembic commands ###
