"""Add print_count to orders

Revision ID: 5c8176ec84df
Revises: b65b0a088d1f
Create Date: 2026-07-28 07:40:16.722745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c8176ec84df'
down_revision: Union[str, Sequence[str], None] = 'b65b0a088d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('print_count', mysql.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'print_count')
    # ### end Alembic commands ###
