"""add status to seller_messages

Revision ID: 88e7d9612ed6
Revises: 0b911fc87174
Create Date: 2026-08-06 08:03:23.522736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e7d9612ed6'
down_revision: Union[str, Sequence[str], None] = '0b911fc87174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_messages', sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ'), server_default='SENT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_messages', 'status')
    # ### end Alembic commands ###
