"""Add unique constraint to tracking_code

Revision ID: 8e224512f383
Revises: 16af620daefa
Create Date: 2026-08-11 03:28:51.177261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e224512f383'
down_revision: Union[str, Sequence[str], None] = '16af620daefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shipments', ['tracking_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='unique')
    # ### end Alembic commands ###
