"""create notification table

Revision ID: 97c34cf5edba
Revises: 3bfb83407eba
Create Date: 2026-07-30 16:18:33.193665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97c34cf5edba'
down_revision: Union[str, Sequence[str], None] = '3bfb83407eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False))
    op.add_column('notifications', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('notifications', sa.Column('action_url', sa.String(length=500), nullable=True))
    op.alter_column('notifications', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('notifications', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint(op.f('notifications_ibfk_1'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'reference_type')
    op.drop_column('notifications', 'read_at')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'reference_id')
    op.add_column('seller_statistics', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('support_messages', 'sender_type',
               existing_type=mysql.ENUM('CUSTOMER', 'SUPPORTER', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('CUSTOMER', 'SUPPORTER', 'SYSTEM'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('support_messages', 'sender_type',
               existing_type=sa.Enum('CUSTOMER', 'SUPPORTER', 'SYSTEM'),
               type_=mysql.ENUM('CUSTOMER', 'SUPPORTER', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('seller_statistics', 'updated_at')
    op.add_column('notifications', sa.Column('reference_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('notification_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('notifications', sa.Column('read_at', mysql.DATETIME(), nullable=True))
    op.add_column('notifications', sa.Column('reference_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('notifications', sa.Column('recipient_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_ibfk_1'), 'notifications', 'users', ['recipient_id'], ['id'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('notifications', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.BIGINT(unsigned=True),
               existing_nullable=False)
    op.drop_column('notifications', 'action_url')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
