"""Add shipping providers

Revision ID: a524958c1990
Revises: 7dd79c32a838
Create Date: 2026-08-10 17:56:50.197631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a524958c1990'
down_revision: Union[str, Sequence[str], None] = '7dd79c32a838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_providers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.CHAR(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('public_id')
    )
    op.drop_constraint(op.f('ck_seller_profiles_shipping_fee'), 'seller_profiles', type_='check')
    op.drop_column('seller_profiles', 'shipping_provider_name')
    op.drop_column('seller_profiles', 'shipping_fee')
    op.add_column('shipments', sa.Column('shipping_provider_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('shipments', sa.Column('tracking_code', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'shipments', 'shipping_providers', ['shipping_provider_id'], ['id'])
    op.drop_column('shipments', 'shipping_provider_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('shipping_provider_name', mysql.VARCHAR(length=150), nullable=True))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'tracking_code')
    op.drop_column('shipments', 'shipping_provider_id')
    op.add_column('seller_profiles', sa.Column('shipping_fee', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('(0.00)'), nullable=False))
    op.add_column('seller_profiles', sa.Column('shipping_provider_name', mysql.VARCHAR(length=150), nullable=True))
    op.create_check_constraint(op.f('ck_seller_profiles_shipping_fee'), 'seller_profiles', '(`shipping_fee` >= 0)')
    op.drop_table('shipping_providers')
    # ### end Alembic commands ###
