"""Add support chat models

Revision ID: c76a30ca5814
Revises: 5c8176ec84df
Create Date: 2026-07-30 03:47:05.905445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c76a30ca5814'
down_revision: Union[str, Sequence[str], None] = '5c8176ec84df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_conversations',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('guest_id', sa.String(length=255), nullable=True),
    sa.Column('supporter_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_conversations_customer_id', 'support_conversations', ['customer_id'], unique=False)
    op.create_index('ix_support_conversations_guest_id', 'support_conversations', ['guest_id'], unique=False)
    op.create_index('ix_support_conversations_status', 'support_conversations', ['status'], unique=False)
    op.create_index('ix_support_conversations_supporter_id', 'support_conversations', ['supporter_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'SUPPORTER'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_messages_conversation_id', 'support_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_messages_conversation_id', table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index('ix_support_conversations_supporter_id', table_name='support_conversations')
    op.drop_index('ix_support_conversations_status', table_name='support_conversations')
    op.drop_index('ix_support_conversations_guest_id', table_name='support_conversations')
    op.drop_index('ix_support_conversations_customer_id', table_name='support_conversations')
    op.drop_table('support_conversations')
    # ### end Alembic commands ###
